# Change these first
owner: teamgreyfinch # Your GitHub organization or username, where this repository lives
repo: public-status # The name of this repository

sites:
  - name: Greyfinch Website
    url: https://greyfinch.com/
  - name: Greyfinch Application
    url: https://app.greyfinch.com/
  - name: Appointments Widget
    url: https://appointments.greyfinch.com/?division=981581
  - name: Patient Hub API
    url: https://api.greyfinch.com/v1/graphql
  - name: Appointments API 
    url: https://app.greyfinch.com/rest/v1/public/divisions/981581/locations

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /public-status
  logoUrl: https://greyfinch.com/wp-content/uploads/2021/03/GreyfinchLogoFinalBig-1536x517.png
  name: Greyfinch status
  introTitle: "Greyfinch Uptime and Status Monitor"
  introMessage: Realtime status monitoring of core Greyfinch applications
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
