# Change these first
owner: teamgreyfinch # Your GitHub organization or username, where this repository lives
repo: public-status # The name of this repository

sites:
  - name: PMS App - https://app.greyfinch.com/
    url: https://app.greyfinch.com/
  - name: Admin/Comms App - https://admin.greyfinch.com/
    url: https://admin.greyfinch.com/
  - name: Patient Hub - https://hub.greyfinch.com/
    url: https://hub.greyfinch.com/
  - name: Appointments Widget
    url: https://appointments.greyfinch.com/?division=981581
    icon: https://raw.githubusercontent.com/teamgreyfinch/public-status/master/assets/cropped-favgreen-01-1-192x192.png
  - name: Appointments API 
    url: https://app.greyfinch.com/rest/v1/public/divisions/981581/locations
    icon: https://raw.githubusercontent.com/teamgreyfinch/public-status/master/assets/cropped-favgreen-01-1-192x192.png
  - name: API - https://api.greyfinch.com/
    url: https://api.greyfinch.com/healthz
    icon: https://raw.githubusercontent.com/teamgreyfinch/public-status/master/assets/cropped-favgreen-01-1-192x192.png
    # https://hasura.io/docs/latest/graphql/core/api-reference/health.html
    __dangerous__body_down: WARN
  - name: Website - https://greyfinch.com/
    url: https://greyfinch.com/
    icon: https://raw.githubusercontent.com/teamgreyfinch/public-status/master/assets/cropped-favgreen-01-1-192x192.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /public-status
  logoUrl: https://raw.githubusercontent.com/teamgreyfinch/public-status/master/assets/cropped-favgreen-01-1-192x192.png
  favicon: https://raw.githubusercontent.com/teamgreyfinch/public-status/master/assets/cropped-favgreen-01-1-192x192.png
  robotsText: "User-agent: * \n Disallow: /"
  name:  Greyfinch Production
  introTitle: "Greyfinch Uptime and Status Monitor"
  introMessage: Realtime status monitoring of Greyfinch applications
  navbar:
    - title: Production
      href: https://teamgreyfinch.github.io/public-status/
    - title: Staging
      href: https://teamgreyfinch.github.io/staging-status/
    - title: Demo
      href: https://teamgreyfinch.github.io/demo-status/
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO
i18n:
  footer: Powered by [Upptime](https://upptime.js.org) 

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
